name: Genera eseguibile Python

on:
  push:
    branches: [ "master" ]

jobs:
  build_amd64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install curl
      run: sudo apt-get install -y libcurl4-openssl-dev
  
    - name: Build executable
      run: make all
      working-directory: ${{ github.workspace }}
      

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ss_mal_x64
        path: ss_mal
        
  build_arm64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2

    - name: Install curl
      run: sudo apt-get install -y libcurl4-openssl-dev
  
    - name: Build executable
      run: make all
      working-directory: ${{ github.workspace }}
      

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ss_mal_arm64
        path: ss_mal

