name: Genera eseguibile Python

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build executable
      run: make all
      working-directory: ${{ github.workspace }}
      

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/backdoorcreate

